@echo off
@REM echo Building UI library...
@REM call npx nx build ui

echo Skipping UI library build (consumed directly by apps)...

echo Building app-shell...
call npx nx build app-shell --configuration=production

echo Building app-one...
call npx nx build app-one --configuration=production

echo Building app-two...
call npx nx build app-two --configuration=production

echo All builds completed!
