version: '3.8'

services:
  app-shell:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-shell
    ports:
      - "4200:80"
    environment:
      - APP_ONE_URL=http://localhost:4201
      - APP_TWO_URL=http://localhost:4202
    depends_on:
      - app-one
      - app-two
    networks:
      - microfrontend-network

  app-one:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-one
    ports:
      - "4201:80"
    networks:
      - microfrontend-network

  app-two:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-two
    ports:
      - "4202:80"
    networks:
      - microfrontend-network

networks:
  microfrontend-network:
    driver: bridge